### PR TITLE
Added support regex for authorized_ip list items

### PR DESCRIPTION
**Pull request by carsongee**

### CODE REVIEW

**Comment by andreipradan** [comment]
The reason why we haven't integrated this pr so far is because we are considering implementing this functionality with [ipaddress](https://docs.python.org/3/library/ipaddress.html) for manipulating ip addresses and networks.

**Comment by carsongee** [comment]
Cool, that would suit my needs since I am just doing big CIDR blocks anyway, but I can imagine some use cases where regex would allow the list to be a little less verbose, i.e. `192.168.22(3|7).+` instead of `['192.168.223.0/24', '192.168.227.0/24']`. Especially if you have a handful of random IPs on a block that need to health check, but CIDRs are more explicit and clear.

**Comment by andreipradan** [comment]
@carsongee 
The functionality we talked about is integrated here:
https://github.com/pbs/django-heartbeat/pull/9
It's already on pypi also.
If it's ok with you we'll close this PR.

**Comment by carsongee** [comment]
Awesome

**Pull request closed without merging**
